### Get resource groups
GET http://localhost:3000/api/resource-groups

### Create resource group
POST http://localhost:3000/api/resource-groups
Content-Type: application/json

{
    "name": "my-rg",
    "stackName": "my-rg"
}

### Delete resource group
DELETE http://localhost:3000/api/resource-groups/my-rg

### Get repositories

GET http://localhost:3000/api/repositories

### Create repositories
POST http://localhost:3000/api/repositories
Content-Type: application/json

{
    "name": "my-repo",
    "stackName": "my-repo",
    "resourceGroupStack": "my-stack",
}

### Delete repositories
DELETE http://localhost:3000/api/repositories/some-stack